---
meta:
  name:    freetds
  target:  pipes@cfcommunity
  url:     https://pipes.starkandwayne.com

  git:
    email:  ((git-commit-email))
    name:   'Stark & Wayne CI Bot'

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-2
    access_key:  ((aws-cfcommunity.access))
    secret_key:  ((aws-cfcommunity.secret))

  github:
    owner:  starkandwayne
    repo:   (( concat meta.name "-buildpack" ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack.username))
    icon:          ((slack.icon))
    channel:       "#freetds-buildpack"
